# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: bd/design_1/design_1.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1 || ORIG_REF_NAME==design_1} -quiet] -quiet

# XDC: c:/Users/Admin/OneDrive/Desktop/Vivado/project_1/project_1.gen/sources_1/bd/design_1/design_1_ooc.xdc
